enable-plugin: false
stacking:
  max-stack-size: 64
  radius:
    x: 3
    y: 3
    z: 3
  separation:
    age:
      enable: true
      strict: false
  names:
    enable: true
    name: '&6&l%COUNT%&r &7%TYPE%'
  exempt:
    use-as-whitelist: false
    types:
      - 'VILLAGER'
triggers:
  per-world:
    use-as-whitelist: true
    worlds:
      - 'Factions'
  events:
    spawn: true
    chunk-load: true
  periodic:
    enable: false
    period: 6
do-not-touch-version: 1