name: ${project.name}
main: ${project.groupId}.mobstacker.MobStackerPlugin
version: ${project.version}
author: A248
description: ${project.description}
depend: [ArimAPI]

commands:
  mobstacker:
    usage: /mobstacker
    description: MobStackerReloaded commands